name: flutter_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.2.6
  path_provider: ^2.0.15
  path: ^1.9.0
  sqlite3_flutter_libs: ^0.5.28
 


dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  
flutter:
  uses-material-design: true
